#!/usr/bin/env bash
# modules/05-bootloader.sh — Bootloader phase
# Boot entries are generated by nixos-install itself (systemd-boot UKIs or
# lanzaboote-signed images, depending on the host profile). This phase
# verifies them and, when the firmware is in Setup Mode, enrolls the Secure
# Boot keys (sbctl) so lanzaboote hosts boot without a manual step.

run_bootloader() {
    if [[ "$DRY_RUN" == "true" ]]; then
        run "verify boot entries (dry)" true
        run "sbctl enroll (dry)" true
        return 0
    fi

    # ── Boot entries ────────────────────────────────────────────────
    local entries=0
    if [[ -d /mnt/boot/loader/entries ]]; then
        entries=$(find /mnt/boot/loader/entries -name '*.conf' 2>/dev/null | wc -l)
        log_ok "systemd-boot entries found: $entries"
    fi
    if [[ -d /mnt/boot/EFI/Linux ]]; then
        local ukis
        ukis=$(find /mnt/boot/EFI/Linux -name '*.efi' 2>/dev/null | wc -l)
        log_ok "lanzaboote UKIs found: $ukis"
        entries=$(( entries + ukis ))
    fi
    if [[ "$entries" -eq 0 ]]; then
        log_fail "no boot entries under /mnt/boot — boot will fail"
        return 1
    fi

    # ── Secure Boot enrollment (optional, Setup Mode only) ──────────
    if ! command -v sbctl > /dev/null 2>&1; then
        log_warn "sbctl not available in live env — enroll after first boot:"
        log_warn "  sbctl create-keys && sbctl enroll-keys --microsoft"
        return 0
    fi

    if sbctl status 2>/dev/null | grep -q "Setup Mode: Enabled"; then
        log_info "UEFI in Setup Mode — creating and enrolling keys"
        log_cmd "sbctl create-keys" sbctl create-keys
        log_cmd "sbctl enroll-keys (with Microsoft keys)" sbctl enroll-keys --microsoft
        log_ok "Secure Boot keys enrolled — enable Secure Boot in firmware after reboot"
    else
        log_info "UEFI not in Setup Mode — skipping enrollment (do it post-boot)"
    fi

    log_system_snapshot "post-bootloader"
    return 0
}
